name: release

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: ubuntu-latest

    steps:
      - name: Initialize Git user
        run: |
          git config --global user.name 'tramvai-conductor'
          git config --global user.email 'tramvai-conductor@users.noreply.github.com'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build packages
        run: |
          yarn build
          git diff --exit-code || (echo "Найдены изменения в файлах package.json – выполните `yarn build` в корне репозитория и запушьте изменения" && exit 127)

      - name: Release packages
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}

      - name: Publish docs
        run: yarn docs:publish
        env:
          GIT_USER: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}
